---
Comment.date_time_format: M d, Y
Comment.feed_limit: 10
Comment.level: 1
Hook.bootstraps: tinymce,example,clipping
Meta.description: 'Media Clipping'
Meta.generator: 'Media Clipping'
Meta.keywords: Media, Clipping, media, clipping
Meta.robots: index, follow
Reading.date_time_format: D, M d Y H:i:s
Reading.nodes_per_page: 5
Service.akismet_key: your-key
Service.akismet_url: http://h8si.com.br
Service.recaptcha_private_key: your-private-key
Service.recaptcha_public_key: your-public-key
Site.email: comercial@h8si.com.br
Site.feed_url: 
Site.locale: eng
Site.status: 1
Site.tagline: Media Clipping.
Site.theme: 
Site.timezone: 0
Site.title: Media Clipping
Writing.wysiwyg: 1
